### ISSUE TITLE
Errors after updating an entity.

### ISSUE THREAD

**Issue by davidsbond** [davidsbond/MyMoney#32]
The current implementation for updating objects in entity framework is not correct. Currently we are obtaining the object, removing it and creating an updated version with a new ID. This needs to be changed to do a proper update.

Here's how to do it properly:
http://stackoverflow.com/questions/15336248/entity-framework-5-updating-a-record

In the provided link, method 3 seems to be the one we want.

**Comment by TJ380** [comment]
During my short stint of research a week ago, I'd agree that method 3 is the way to go. I can take a look at this on the weekend.

**Comment by TJ380** [comment]
Completed in pull request #37.
