### ISSUE TITLE
DatabaseContext declarations in repositories should use 'var'

### ISSUE THREAD

**Issue by davidsbond** [davidsbond/MyMoney#39]
In each repository layer we have the following:

```csharp
using(DatabaseContext context = new DatabaseContext())
{
 ...
}
```

The double declaration of the type is a bit redundant and increases line length. This should be changed to:

```csharp
using(var context = new DatabaseContext())
{
 ...
}
```

We should use 'var' whenever possible.

**Comment by TJ380** [comment]
Completed in PR #45
